sudo: required
language: cpp
services: docker
before_install:
  - docker build -t laser-stripping .
script:
  - docker run laser-stripping  bash -c "source /pyORBIT/setupEnvironment.sh; cd examples;./START.sh 1GeV-particle-stripping.py 2"
  
